services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: Agentic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Str0ng4gent!cP@55word
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      
volumes:
  database_data:
