@WebApi_HostAddress = https://localhost:7048

POST {{WebApi_HostAddress}}/api/principles
Accept: application/json
Content-Type: application/json

{
  "name":"My First Principle",
  "content": "Hello there"
}

###
